name: tests

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: make gradlew executable
        run: chmod +x gradlew

      - name: run tests
        run: ./gradlew :app:testReleaseUnitTest

      - name: upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: app/build/reports/tests/testReleaseUnitTest/**
          retention-days: 2
